name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Addition test
      id: addition-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Addition test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_addition.py --pylint
        timeout: 10
        max-score: 10
    - name: Subtraction Test
      id: subtraction-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Subtraction Test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_subtraction.py --pylint
        timeout: 10
        max-score: 10
    - name: Multiplication Test
      id: multiplication-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Multiplication Test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_multiplication.py --pylint
        timeout: 10
        max-score: 10
    - name: Division Test
      id: division-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Division Test
        setup-command: pip install -r requirements.txt
        command: pytest tests/test_division.py --pylint
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADDITION-TEST_RESULTS: "${{steps.addition-test.outputs.result}}"
        SUBTRACTION-TEST_RESULTS: "${{steps.subtraction-test.outputs.result}}"
        MULTIPLICATION-TEST_RESULTS: "${{steps.multiplication-test.outputs.result}}"
        DIVISION-TEST_RESULTS: "${{steps.division-test.outputs.result}}"
      with:
        runners: addition-test,subtraction-test,multiplication-test,division-test
